main: dev.rotator.pvplabs.PvPLabs
name: PvPLabs
api-version: 1.21
version: 0.1.2
commands:
  party:
    aliases: [p]
    description: "Command for parties"
    usage: "§c/p accept/leave/list/invite"
  duel:
    description: "(beta) Duel a player"
    usage: "§c/duel <player>"
  rotatordebug:
    description: "secret admin debug command hehehe"